stages:
- build-and-test
- combine
- upload

buildjs:
  stage: build-and-test
  script:
  - yarn
  - yarn build
  artifacts:
    paths:
    - lib/*
    expire_in: 1 week

testjs:
  stage: build-and-test
  script:
  - yarn
  - yarn lint

build:
  stage: combine
  tags:
    - senses
  script:
  - minc cp iots3/homeiot/artifacts/senses.tar senses.tar
  - tar xvpf senses.tar
  - mv dist www
  - yarn build:dist
  artifacts:
    paths:
    - dist/senses.sqfs
    expire_in: 1 week

uploaddist:
  stage: upload
  only:
  - master
  script:
  - minc cp dist/senses.sqfs iots3/homeiot/artifacts/senses.sqfs
