enum TurnState {
    on
    off
    unknown
}

type DeviceInfo {
    product: String
    productCode: String
    vendor: String
    vendorId: String
    model: String
    serialNumber: String
    revision: String
    driver: String
}

type Device {
    uid: ID!
    name: String
    type: String
    class: String
    kind: String
    title: String
    description: String
    entityId: String!
    room: String
    groups: [Group]
    info: DeviceInfo
    available: Boolean
    lastAlive: Date
    keepalive: Boolean
    lastUpdate: Date
    timeout: Int
    turnable: Boolean
    turn: TurnState
    state: JSONObject
    extraAttrs: JSONObject
    features: [String]
    tags: [String]
    via: ID
}

type Group {
    name: String!
    title: String
    description: String
    type: String!
}

extend type Query {
    devices(filter: JSONObject): [Device]
    device(uid: ID!): Device!
}

extend type Mutation {
    setState(deviceUid: String!, newState: JSONObject!): Boolean
}

extend type Subscription {
    deviceUpdated: Device
}
