domain: roztoky

http:
  port: 8080

mqtt:
  brokerUrl: mqtts://127.0.0.1
  options:
    caFile: certs/ca.cert
    certFile: certs/client.cert
    keyFile: certs/client.key
    rejectUnauthorized: false

expose:
  enabled: yes

watcher:
  interval: 1000

test: !include lol

device:
  discovery: true
  devices:
    # Světlo v kuchyni
    - name: kitchen_light
      title: Kuchyně - světlo
      type: light
      class: light
      room: kitchen
      publisher:
        - topic: modbus/gw0/kitchenlight0/+_name/set
          format: number
        - topic: modbus/gw0/kitchenlight0/set
      subscriber: 
        - topic: modbus/gw0/kitchenlight0/state
      poll:
        - modbus/gw0/kitchenlight0/get
      features: [colorTemp, brightness]
      availability:
        - topic: modbus/gw0/kitchenlight0/presence
          payload_available: online
          payload_unavailable: offline
    - name: temperature
      title: Teplota v místnosti
      class: temperature
      room: kitchen
      type: sensor
      groups: [room.kitchen]
      subscriber: 
        - topic: device/roztoky/kitchen/heater
      mainField: temperature
      fields:
        temperature:
          title: Teplota
          type: temperature
      tags:
        - main

room:
  - name: kitchen
    title: Kuchyně
    icon: rooms/kitchen
  - name: bathroom
    title: Koupelna
    icon: rooms/bath
  - name: bedroom
    title: Ložnice
    icon: rooms/bedroom
  - name: sanctuary
    title: Klidová místnost
    icon: rooms/livingroom
  
scene:
  - name: night
    title: Noc
    icon: img/nightmoon
  - name: kitchen_night
    title: Noc
    room: kitchen
