domain: roztoky

http:
  port: 8080

mqtt:
  brokerUrl: mqtt://127.0.0.1

expose:
  enabled: yes

watcher:
  interval: 1000

test: !include lol

device:
  discovery: true
  devices:
    # Světlo v kuchyni
    - name: kitchen_light
      title: Kuchyně - světlo
      type: light
      class: light
      room: kitchen
      publisher:
        - topic: modbus/gw0/kitchenlight0/+name/set
          format: number
      subscriber: 
        - topic: modbus/gw0/kitchenlight0/state
      features: [colorTemp, brightness]
      availability:
        - topic: modbus/gw0/kitchenlight0/presence
          payload_available: online
          payload_unavailable: offline
    - name: temperature
      title: Teplota
      class: temperature
      room: kitchen
      type: sensor
      groups: [room.kitchen]
      stateTopic: device/roztoky/kitchen/heater
      field: temperature
      tags:
        - main

room:
  - name: kitchen
    title: Kuchyně
    icon: rooms/kitchen
  - name: bathroom
    title: Koupelna
    icon: rooms/bath
  - name: bedroom
    title: Ložnice
    icon: rooms/bedroom
  - name: relaxroom
    title: Relaxační místnost
    icon: rooms/livingroom
  
scene:
  - name: night
    title: Noc
    icon: img/nightmoon
    entities:
      light.kitchen_light:
        brightness: 10
        switch: 0
  - name: kitchen_night
    title: Noc
