domain: roztoky

http:
  port: 8080

mqtt:
  brokerUrl: mqtt://127.0.0.1

expose:
  enabled: yes

test: !include lol

light:
  # Světlo v kuchyni
  - name: kitchen_light
    title: Kuchyně - světlo
    platform: mqtt
    class: light
    commandTopic: modbus/gw0/kitchenlight0/set
    stateTopic: modbus/gw0/kitchenlight0/state
    features: [colorTemp, brightness]
    availability:
      - topic: modbus/gw0/kitchenlight0/presence
        payload_available: online
        payload_unavailable: offline

room:
  - name: kitchen
    title: Kuchyně
    icon: img/kitchen
    entities:
      - light.kitchen_light
      - scene.kitchen_night
  - name: .home
    entities:
      - scene.night

scene:
  - name: night
    title: Noc
    icon: img/nightmoon
    entities:
      light.kitchen_light:
        brightness: 10
        switch: 0
  - name: kitchen_night
    title: Noc
